// https://projecteuler.net/problem=2

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 **/

#include <stdio.h>

int main() {
    int a = 1;
    int b = 2;

    int sum = 2;

    while (1) {
        int c = a + b;
        if (c > 4000000) {
            break;
        }
        if (c % 2 == 0) {
            sum += c;
        }
        if (a > b) {
            b = c;
        } else {
            a = c;
        }
    }
    printf("Result: %d\n", sum);

    return 0;
}